export const styles = {
  mainView: {
    paddingHorizontal: 38,
    paddingBottom: 24,
    paddingTop: 28,
    backgroundColor: 'white',
  },
  mainTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  title: {
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 18,
    lineHeight: 28,
    color: '#F1800D',
  },
  subtitle: {
    fontFamily: 'Nunito Sans',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 16,
    lineHeight: 22,
    color: 'rgba(38, 50, 56, 0.7)',
    marginBottom: 24,
  },
  input: {
    paddingHorizontal: 0,
    fontFamily: 'Nunito Sans',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 14,
    lineHeight: 14,
    borderBottomColor: 'rgba(38, 50, 56, 0.1)',
    color: 'rgba(38, 50, 56, 0.4)',
  },
  crossIcon: {
    fontFamily: 'Montserrat',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 20,
    textAlign: 'center',
    color: '#FFFFFF',
    width: 10,
    height: 20,
  },
  crossBack: {
    backgroundColor: '#263238',
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 50,
  },
  tabView: {
    paddingHorizontal: 38,
    backgroundColor: 'white',
    paddingTop: 4,
    paddingBottom: 24,
  },
  tabBarIndicator: {
    backgroundColor: '#F1800D',
  },
};
